linters-settings:
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 15
  gomnd:
    settings:
      mnd:
        ignored-numbers: 100
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - deadcode
    - decorder
    - depguard
    - depguard
    - dogsled
    - dupl
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - go-critic
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocognit
    - goconst
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - godox
    - goerr113
    - gofumpt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - maintidx
    - megacheck
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

issues:
  exclude-use-default: false
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - ifshort
